# This Makefile automatically generated by configure.

CC =		cc
CFLAGS =	-g -O2 -pipe -w   -I/Users/caseycronyn/Developer/bristol/major-project/oed -I/opt/homebrew/opt/readline/include
LDFLAGS = -L/opt/homebrew/opt/readline/lib 
LIBS    = -lreadline -lhistory -lncurses
WARNS := $(CFLAGS) -Wall -Wextra -Wfloat-equal -Wvla -Wpedantic
OPTIM := $(WARNS) -O3
DEBUG := $(WARNS) -fsanitize=undefined -fsanitize=address -g3

PREFIX =	/usr/local
MANDIR =	/usr/local/man

PROG =	oed
OBJS =	buf.o glbl.o io.o main.o re.o sub.o undo.o \
	regcomp.o regerror.o regexec.o regfree.o \
	reallocarray.o strlcat.o strlcpy.o readline.o lsp.o cJSON.o

all: ${PROG}

deb: ${OBJS}
	${CC} ${LDFLAGS} -o deb ${OBJS} ${LIBS} ${DEBUG}

${PROG}: ${OBJS}
	${CC} ${LDFLAGS} -o ${PROG} ${OBJS} ${LIBS}

install:
	install -d ${DESTDIR}${PREFIX}/bin
	install -d ${DESTDIR}${MANDIR}/man1
	install -c -s -m 755 ${PROG} ${DESTDIR}${PREFIX}/bin
	install -c -m 644 ed.1 ${DESTDIR}${MANDIR}/man1/${PROG}.1

test:
	@echo "No tests"

clean:
	rm -f ${PROG} ${OBJS}

distclean: clean
	rm -f Makefile config.h


